### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by geekyayush** [saas-js/saas-ui-nextjs-landing-page#1]

**Comment by Pagebakers** [comment]
Haven't had enough time to keep it up to date, but planning to give this a refresher soon!

**Comment by geekyayush** [comment]
> Haven't had enough time to keep it up to date, but planning to give this a refresher soon!

It would be awesome if this can be updated ^_^
Thanks!

**Comment by Pagebakers** [comment]
All packages and deps have been updated.
